
debug: false
management.endpoints.web.exposure.include: "*"

logging:
    level:
        '[com.project.scheduler]': debug
        '[org.springframework.web]': debug
        '[org.hibernate.type.descriptor.sql.BasicBinder]': trace

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/JAVA_WEB?characterEncoding=UTF-8&serverTimezone=UTC
        username: simpleweb
        password: simpleweb
    sql.init.mode: always
    data.rest:
        base-path: /api
        detection-strategy: annotated

# mybatis 관련 설정
mybatis:
  mapper-locations: mapper/*.xml